// Generated by CoffeeScript 1.3.3
(function() {
  var root;

  root = this;

  /*
   A list of comment div selectors sourced from Steven Frank's awesome shutup.css
   http://stevenf.com/shutup-css/
  */


  root.filler_selector_list = ["#watch-comment-panel", "#cm", "#watch-comments-core", ".comments", "#comments", "#disqus_thread", "#dsq-content", ".block-talkback_story", "#prodReviews", ".revcontent", ".commentlist", "#commentlist", "#commentlisting", "#socialcomments", ".commentwrapper", ".commentarea", ".comment", "#commentform", ".commentText", "#pluckcomments", "#pluck-comments", ".pluck-comm", "div#page div#content h2#shoutbox, div#page div#content div#shoutboxContainer", "#latest-comments", ".commentHolder", ".comments-list", "#blogComments", "#comments_pane", "#commentcontainer", "#commentsDiv", ".comment-container", "#comment-container", "#comment_container", "#commentblob", "#cnnComments", "#BrowseComments", ".mwpphu-comments", ".ugccmt-comments", ".comments-body", ".articleComments", ".page-comments", "#gmi-CCommentMaster", ".comments-container", "#media_comments", "#idc-container-parent", "#livefyre-body", "#articleComments", ".js-CommentsArea", "#readerComments", ".readerComments", ".commentsModule", ".dna-comment", ".view-6", ".space-_5", ".all_comments", "#display_comments", ".article-comments", "#commentscontainer", ".echo-stream-container", "#feedback", ".Comments", "#lf_comments", "#lf_twitter_comments", "#lf_facebook_comments", "#commentList", "#inferno-comments", ".cb_block", ".CMT_CommentList", "#comments_section", ".fb-comments", "#responses", "#facebook_responses", ".spCommentsBoxBody", ".kommentare_uebersicht", "#body_dlt", "#ugc-container", ".ArtikelKommentieren", ".comment-avatar-wrap", ".fbFeedbackContent", ".discussionContainer", ".commentBoxStyle", ".pagecomment", ".pagecommentheader", ".com_text", ".commenttxt", ".post-comment-list"];

}).call(this);
